### PR TITLE
Expose database to templates

### PR DESCRIPTION
**Pull request by spbnick**
Expose all test suites and their cases from the database to the templates, as well as the source path set and functions for matching test suites and test cases against them.

This will let templates be aware of test suite and test case objects and make better decisions.
This prepares for the addition of template-visible suite-level parameters.

Supersedes #51.

### CODE REVIEW

**Review by wizardofoz123 — APPROVED** [review]
This is a rather big change, but the code looks OK.
I'm not sure why to coverage is reported as first build, it should show about 5% coverage decrease.
Ideally the coverage should remain the same, but feel free to merge this or adjust as you see fit.

**Comment by spbnick** [comment]
Thank you, Jakub! Yes, coverage needs improvement, and coveralls noted 4.2% decrease.

@cki-bot, could you please test this?

**Comment by spbnick** [comment]
All the tests that could start, completed successfully.

**Comment by spbnick** [comment]
I will work on improving coverage in following PRs. Merging this now.

**Pull request merged**
