### PR TITLE
add hostname attribute for overwriting hostRequires

### PR DESCRIPTION
**Pull request by wizardofoz123**
This is kpet change necessary to implement FASTMOVING-740.

This patch adds hreq_forced attribute into host. This attribute contains
the first string from yaml that contains 'hostRequires force'
substring; cases are scanned first, then suites.

This allows kpet-db jinja template to insert <hostRequires force="..." />
element insteadof any normal hostRequires.
This change is independent from kpet-db, but in order to work, kpet-db
hostRequires files have to be deleted and XML snippets moved to yaml.

Signed-off-by: Jakub Racek <jracek@redhat.com>

### CODE REVIEW

**Comment by spbnick** [comment]
I'm sorry, but this will be difficult to understand and keep in mind, as well as maintain, so no-go from my side.
Also, please avoid Beaker-specific terminology and features if at all possible. We want to be *less* coupled to it, not more, even if we never get rid of it, let alone if we want to move to something else. This also concerns recipeSets which we already have and which will need to go.

Keep features as generic and abstract as possible. In this case all we need to express is that we need a particular hostname. So, please see if you can simply add a field called "hostname" to the host type, transfer that to run.Host upon creation, and use it in the template when generating the `<hostRequires>` tag.

**Comment by wizardofoz123** [comment]
@spbnick I agree with what you're saying about Beaker terminology and also think it should be separate.
However, some of the concepts in kpet-db are Beaker specific. For example, renaming "recipeSets" to something like "synchronization domains" would be more general, but it could make things for confusing for QE. The only other solution I can think of quickly is to have some kindof interface between Beaker/non-Beaker -specific parts.

Would the content of this PR be difficult to maintain because of the Beaker specifics, or because of different reasons?

At any rate, I'll rework this PR. Thanks for feedback, much appreciated!

**Comment by spbnick** [comment]
The approach in this PR would be difficult to maintain for several reasons, but one reason would be because one doesn't normally expect template contents to affect behavior outside the template. If it was just naming, I would only ask for a naming update :)

The recipeSets is a difficult one in that regard, yes, but I'm thinking we might not needed it in that shape at all, so it wouldn't be a problem. Don't have anything to talk about at this moment, though.

**Comment by spbnick** [comment]
Thank you, Jakub, this looks much better :) However, let's not add `hostname` to anything but the host types. We can already assign host type regex both at suite and case levels, and different hostnames at different (host/suite/case) levels would be an invalid case and doesn't really make sense. Plus it requires all kinds of tricks to implement in kpet-db, as you're doing at the moment. Simply paste the value of host's `hostname` into the `force` attribute with only one condition: if it's set.

**Pull request merged**
