### PR TITLE
Use the http endpoint for the CA certs

### PR DESCRIPTION
**Pull request by mh21**
Signed-off-by: Michael Hofmann <mhofmann@redhat.com>

### CODE REVIEW

**Comment by mh21** [comment]
@cki-bot  please test

**Comment by rasibley** [comment]
I don't think this will work since RHEL5 doesn't support update-ca-trust, it uses cacertdir_rehash command instead. Also certs live in /etc/pki/tls/certs vs /etc/pki/ca-trust/source/anchors.

**Comment by spbnick** [comment]
These are just test assets, and they don't get submitted to Beaker, but if we're doing the same thing in kpet-db, it would be good to sync those.

**Comment by veruu** [comment]
@mh21 should we close this?

**Comment by mh21** [comment]
Oh yes this pull request shows my ignorance of everything related to kpet :see_no_evil:

**Pull request closed without merging**
