### PR TITLE
`--db` parameter global, required and `help` command removed

### PR DESCRIPTION
**Pull request by agustinhenze**
Otherwise to use the `help` command you should pass `--db` as parameter which is really counter intuitive. I think it's a good trade off lack of `help` command but have `--db` parameter as required.

### CODE REVIEW

**Comment by agustinhenze** [comment]
Pls don't merge it yet. I'm adding a test case for this

**Comment by agustinhenze** [comment]
Done, please @spbnick take a look at it now

**Comment by spbnick** [comment]
I really like the simplification, but I'm not sure, yet, if we should remove the `help` entity.

Even though plenty of people expect such an invocation to work (i.e. `kpet help`) for this kind of interface, they will likely survive without it. I'm more worried about us needing to add other entities which won't really need a db, in which case we'll be back to this problem.

So, the fundamental question is what kind of "entity" could that be? What wouldn't need a db, can we make that an option as well? Since it wouldn't need the data, what would it operate on? Will we always need the db specified (on the command line or in the configuration files) for most of the tasks we do?

@agustinhenze, what do you think?

**Comment by spbnick** [comment]
Ah, one thing would be good to go, if this goes in: separate `help` command removal and making `--db` parameter required. Put them into separate commits in that order.

**Comment by agustinhenze** [comment]
> Ah, one thing would be good to go, if this goes in: separate `help` command removal and making `--db` parameter required. Put them into separate commits in that order.

OK, np will do

**Comment by agustinhenze** [comment]
> I really like the simplification, but I'm not sure, yet, if we should remove the `help` entity.
> 
> Even though plenty of people expect such an invocation to work (i.e. `kpet help`) for this kind of interface, they will likely survive without it. I'm more worried about us needing to add other entities which won't really need a db, in which case we'll be back to this problem.
> 
Yes, I think so. Also most of the unix application expects `-h` or `--help` picking three of them randomnly e.g.
```
ls help
ls: cannot access 'help': No such file or directory
find help
find: ‘help’: No such file or directory
dbus-launch help
Couldn't exec help: No such file or directory
```
It doesn't seem too bad having the following output for kpet after all
```
kpet help
usage: kpet [-h] --db DB {run,tree,arch} ...
kpet: error: argument command: invalid choice: 'help' (choose from 'run', 'tree', 'arch')
```

> So, the fundamental question is what kind of "entity" could that be? What wouldn't need a db, can we make that an option as well? Since it wouldn't need the data, what would it operate on? Will we always need the db specified (on the command line or in the configuration files) for most of the tasks we do?
> 

I always prefer avoid adding complexity in the code if it's not really needed. I think that having the --db parameter as optional in some options will require a custom parser therefore if it appears to be needed in the future we can solve it easily.

**Comment by spbnick** [comment]
Programs which follow `PROGRAM OBJECT ACTION` CLI pattern often support `PROGRAM HELP` and sometimes `PROGRAM OBJECT HELP`. E.g. `git help`, `ip help`, `ip route help`, `ipa help`, and so on. Those are often *in addition* to `PROGRAM -h/--help`. It's just what people often expect from this kind of CLI, which is distinct from the one used by classic *nix tools such as `ls` and `find`. That's what I'm referring to.

I would be OK with diverging from that for the sake of simplicity. However, I have a feeling we will need that solved eventually. If we can think of plausible other "entities" which won't need the `--db` option, then I'd rather leave it "entity-specific" and not make it global at all, then.

One example could be a command listing possible values for one of the `kpet run generate` parameters, which are hard-coded, and are not part of the database. I.e. it needs to be `kpet run generate --thingy FOO` and there would need to be `kpet thingy list` producing `FOO, BAR, BAZ`, but `FOO`, `BAR`, and `BAZ` are defined in the source code and don't need the db to be output. So `kpet thingy` wouldn't need the `--db` option. OTOH, we can require it to be supplied anyway in the case we might transition to storing the list in the database after all.

Another consideration is how to structure the (eventual) configuration file, in case the `--db` option is left entity-specific. Should it then be specified separately for each entity type in the configuration file too? Or should it be global there? Coming from this angle, I would say it should be global both in the configuration file and on the command line, but perhaps each entity should verify that it's present by itself. I.e. tell the parser the `--db` is optional, but complain if it's missing in each entity interface which requires it.

Anyway, those are my thoughts and considerations, but I'll leave it up to you to decide how to do it.

However, if you prefer it this way, please consider putting "Remove `help` command" commit *before* "Make `--db` parameter required." before merging, so the help command is not broken at any point while it's still there. Thank you :)

**Review by spbnick — APPROVED** [review]
Looks good, thank you, Agustin!

**Pull request merged**
