### PR TITLE
Test assets to source code

### PR DESCRIPTION
**Pull request by Toaster192**
The first version of embeding test assets to source code, built on top of #72 

Just so we know we're thinking the same changes with @spbnick 

All folders in tests/assets/db/ can now be deleted except general which could also be embeded into the other tests.

I plan on splitting the integration tests more(around 2 more files) since some of them are now over 1k lines :sweat_smile:

### CODE REVIEW

**Comment by Toaster192** [comment]
@cki-bot  Might as well get this test ed

**Comment by spbnick** [comment]
Looks good so far :)

A few minor requests:
* please drop the regex verification stuff from this PR;
* please describe your commits in imperative mood (as if you're commanding things to change), e.g. instead of "Tests refactor and integration tests splitting" write "Refactor tests and split integration tests";
* remember to keep commits logically-separated (you might be intending to in the final version, of course), a good rule of thumb is: if you have to write "and" when describing your change, you need to split it.

**Comment by spbnick** [comment]
Thank you, @Toaster192. This is good overall. I would have liked some things improved, but I don't want to keep you rebasing this forever. So I'd rather merge this earlier.

However, I see that there's still a bunch of files left in the assets:
```
nkondras@bard:~/projects/github.com/cki-project/kpet$ find tests/assets/db/ -type f
tests/assets/db/multihost/no_types/no_regex/two_suites/suite2.yaml
tests/assets/db/multihost/no_types/no_regex/two_suites/suite1.yaml
tests/assets/db/multihost/no_types/db_regex/suite2.yaml
tests/assets/db/multihost/no_types/db_regex/suite1.yaml
tests/assets/db/multihost/two_types/one_case_each/suite2.yaml
tests/assets/db/multihost/two_types/one_case_each/suite1.yaml
tests/assets/db/multihost/two_types/both_cases_first/suite2.yaml
tests/assets/db/multihost/two_types/both_cases_first/suite1.yaml
tests/assets/db/multihost/two_types/both_cases_both/suite2.yaml
tests/assets/db/multihost/two_types/both_cases_both/suite1.yaml
tests/assets/db/multihost/two_types/both_cases_second/suite2.yaml
tests/assets/db/multihost/two_types/both_cases_second/suite1.yaml
tests/assets/db/multihost/one_type/case_regex/suite2.yaml
tests/assets/db/multihost/one_type/case_regex/suite1.yaml
tests/assets/db/multihost/one_type/suite_regex/suite2.yaml
tests/assets/db/multihost/one_type/suite_regex/suite1.yaml
tests/assets/db/multihost/one_type/no_regex/two_suites/suite2.yaml
tests/assets/db/multihost/one_type/no_regex/two_suites/suite1.yaml
tests/assets/db/multihost/one_type/wrong_regex/suite2.yaml
tests/assets/db/multihost/one_type/wrong_regex/suite1.yaml
tests/assets/db/multihost/one_type/db_regex/suite2.yaml
tests/assets/db/multihost/one_type/db_regex/suite1.yaml
tests/assets/db/match/location_types/one_pattern/suite.yaml
tests/assets/db/match/location_types/two_patterns/suite.yaml
tests/assets/db/match/location_types/no_patterns/suite.yaml
tests/assets/db/match/trees/one_pattern/suite.yaml
tests/assets/db/match/trees/two_patterns/suite.yaml
tests/assets/db/match/trees/no_patterns/suite.yaml
tests/assets/db/match/arches/one_pattern/suite.yaml
tests/assets/db/match/arches/two_patterns/suite.yaml
tests/assets/db/match/arches/no_patterns/suite.yaml
tests/assets/db/match/sources/two_cases/suite.yaml
tests/assets/db/match/sources/one_case/one_pattern/suite.yaml
tests/assets/db/match/sources/one_case/two_patterns/suite.yaml
tests/assets/db/match/sources/two_suites/suite2.yaml
tests/assets/db/match/sources/two_suites/suite1.yaml
tests/assets/db/match/sources/specific/suite/suite2.yaml
tests/assets/db/match/sources/specific/suite/suite1.yaml
tests/assets/db/match/sources/specific/case/suite2.yaml
tests/assets/db/match/sources/specific/case/suite1.yaml
tests/assets/db/general/trees/rhel7.xml
tests/assets/db/general/trees/rhel8.xml
tests/assets/db/general/index.yaml
tests/assets/db/general/suites/default/index.yaml
tests/assets/db/general/suites/fs/index.yaml
tests/assets/db/general/suites/fs/partitions.xml
tests/assets/db/general/suites/fs/hostrequires.xml
tests/assets/db/general/rhel7_rendered.xml
```
We can keep the `general` directory, but I expected the rest to go away with this change. What's up with those?

**Comment by Toaster192** [comment]
Oh, that's my bad, those all got changed in master and I forgot to delete them while merging.

Good eye, thanks!

**Comment by Toaster192** [comment]
@spbnick Should be good to go now

**Comment by spbnick** [comment]
Thank you, @Toaster192. I would have more requests, but let's merge the meat of it now, and work on the improvements afterwards.

**Pull request merged**
