### PR TITLE
Remove leftover code for pattern:sets handling

### PR DESCRIPTION
**Pull request by Toaster192**

### CODE REVIEW

**Comment by spbnick** [comment]
We should also remove sets from the `Target` shouldn't we?

**Comment by Toaster192** [comment]
> We should also remove sets from the `Target` shouldn't we?

Ah, my bad, will do

**Comment by spbnick** [comment]
Looks good! Let's what @cki-bot's testing shows.

**Comment by spbnick** [comment]
Pipeline failures seem unrelated. A few local tests showed no issues. Merging!

**Pull request merged**
